"""initial migration

Revision ID: 95c77548f416
Revises: 034e705807f5
Create Date: 2024-02-21 19:20:17.725735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c77548f416'
down_revision = '034e705807f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
